# configuration for benchviz
environment: ''
render:
  title: 'Benchark'
  theme: roma
  chart: barchart
  layout:
    horizontal: 2
  legend: bottom
  scale: auto

outputs:
  htmlFile: ''
  pngFile: ''

metrics:
  - 
    id: nsPerOp
    title: Benchmark Timings
    axis: 'ns/op'
  - 
    id: allocsPerOp
    title: Benchmark Allocations
    axis: 'allocs/op'
  - 
    id: bytesPerOp
    title: Benchmark Memory Usage
    axis: 'bytes/op'
  - 
    id: MBytesPerS
    title: Benchmark Throughput
    axis: 'MB/s'

functions: []
contexts: []
versions: []
categories: []
